MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.9                       # [osx and x86_64]

python:
  - 3.9
  - 3.10
  - 3.11

pin_run_as_build:
  python: x.x

# clang 17 seems to have issues with this build
# specifically cmake detecting std versions
# fixing compiler to clang 16 for now (same as conda-forge atm)
c_compiler:
  - clang                      # [osx]
c_compiler_version:            # [unix]
  - 18                         # [osx]
c_stdlib_version:              # [unix]
  - macosx_deployment_target   # [osx]
cxx_compiler:
  - clangxx                    # [osx]
cxx_compiler_version:          # [unix]
  - 18                         # [osx]
